### ISSUE TITLE
Update README.md to include project info and setup steps.

### ISSUE THREAD

**Issue by AkMo3** [LNMIIT-CODING/stonks-frontend#1]
Update [README.md](https://github.com/LNMIIT-CODING/STONKS-FrontEnd/blob/main/README.md) to include Project information, how to setup project, how to contribute, project tech stack, list of moderators to approach help for specific issue. Modify current [README.md](https://github.com/LNMIIT-CODING/STONKS-FrontEnd/blob/main/README.md) and remove redundant data.

#### Basic Techincal Info
1. Project Based on **React JS**
2. We would be using **Yarn** to setup the project.
3. Tech Stack would include **React JS, PostgreSQL** for now.

EDIT :- List of moderators to approach would be shared shortly.

**Comment by Ayush-Shukla02** [comment]
For the list of moderators to contact can I use the one that was given on the discord server?

**Comment by AkMo3** [comment]
Sure

**Comment by Ayush-Shukla02** [comment]
Whatever was present in the README file beforehand, is to be removed or not?

**Comment by AkMo3** [comment]
Put your content at the top, and refractor the already content upto yarn
build, remove everything below that and put inside the rest inside a
"contribution section".

**Comment by AkMo3** [comment]
@Ayush-Shukla02 
Steps to contribute:
1. **Fork** the repo
2. Take up an issue
3. Write code
4. **Commit** changes in a **new branch**
5. Make a PR

**Comment by Ayush-Shukla02** [comment]
Yes I have made the necessary changes till now in the forked repo. Once completed I will make PR. Or if you say I can make one now to show the current status.
@AkMo3

**Comment by AkMo3** [comment]
Yup, it would be better

**Comment by Ayush-Shukla02** [comment]
I have made the PR

**Comment by Ayush-Shukla02** [comment]
Also check and verify whether the mods' and members' list needs any changes.
And what would be the setup steps?
