### ISSUE TITLE
NavBar Component

### ISSUE THREAD

**Issue by AkMo3** [LNMIIT-CODING/stonks-frontend#14]
Create navbar component for the front page.

mentor - @OmGuptaIND

**Comment by AkMo3** [comment]
I am on it.

Edit: I am not on it, some else can take this issue, just comment I am on it.

**Comment by OmGuptaIND** [comment]
Nav bar is very important so anyone wants to do it ping me I will guide you for it ... 

Just say I am on it and ping me 
..

**Comment by skycodes912** [comment]
i am on it @OmGuptaIND

**Comment by OmGuptaIND** [comment]
@N-coder-bot see header should be with using all the css labelled on the index.css in root selector

You should also keep in mind we need a logo (keep it as a place holder for now) on the left and 3 tabs for now namely Dash Board About and Home on the right and we also want to make them dynamic meaning when a person is on dash board the dashboard tab on the header should be orange 

Color Scheme:
- background-color: var(--main);
- color : var(--text);
- focus color : orange ;

Follow all these ... And if you need any help ping me

**Comment by OmGuptaIND** [comment]
Assigned to @N-coder-bot

**Comment by Ayush-Shukla02** [comment]
I also don't know react. I will try with CSS. @OmGuptaIND

**Comment by OmGuptaIND** [comment]
@Ayush-Shukla02 then dont do it let @N-coder-bot complete it we will have more work for you in the later stage of the project this nav bar is more functionality centric than css part ... 

We will definitely have some CSS work just wait for it

**Comment by skycodes912** [comment]
actually @OmGuptaIND  i dont have any knowledge of React too
sorry :(

**Comment by skycodes912** [comment]
i am not on it :(

**Comment by OmGuptaIND** [comment]
This work is open and its on react 

Please see the specification required mentioned above 

Any problem ping me

**Comment by arcinston** [comment]
i  am on it , @OmGuptaIND pls guide me
im still noob

**Comment by OmGuptaIND** [comment]
Make a header file with all the components like you know how to make a header right ?.

Make a simple Nav Bar for now I will help you with the functionality later make the UI first

@arcinston

**Comment by arcinston** [comment]
yes sir

**Comment by Astha-Singh1729** [comment]
ahhh this is confusing shuklihmm

**Comment by AkMo3** [comment]
Sorry that I had to leave it in middle, I needed to resolve queries in 2 PR and make 2 new PR as well, so didn't had time to work on this. Anyways, [one](https://github.com/checkstyle/checkstyle/pull/9683) is done, one is remaining. Hope I can make it.

You can find a sample Navbar [Navbar](https://github.com/AkMo3/HyperQuestDA-frontend/blob/master/src/components/Navbar.tsx), I had written it some time ago. But it looks ugly, I am not very good with frontend :upside_down_face:

**Comment by OmGuptaIND** [comment]
Closed
