### ISSUE TITLE
Chore: Make a new logo suitable for the project

### ISSUE THREAD

**Issue by OmGuptaIND** [LNMIIT-CODING/stonks-frontend#31]
Follow the steps to add the logo for development purposes:

1. Make a new Images folder inside the src folder and paste the image.
2. Make a new Images folder insider the public folder and paste the image.
2. Add the logo there with the name **logo** only
3. Change the readme file to show the logo on top

**Comment by Ayush-Shukla02** [comment]
Both the images in both folders? @OmGuptaIND 
and which one to add in the README.md, The one with the name STONKS?

**Comment by OmGuptaIND** [comment]
Yes to first and yes to second

**Comment by OmGuptaIND** [comment]
Closed with the PR https://github.com/LNMIIT-CODING/stonks-frontend/pull/33
